[env:m5stick-c-plus2]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.partitions = huge_app.csv
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.mcu = esp32

upload_speed = 115200
upload_resetmethod = nodemcu

lib_deps = 
    https://github.com/m5stack/M5StickCPlus2.git
    links2004/WebSockets@^2.4.1
    arduino-libraries/Arduino_JSON@^0.1.0
    tzapu/WiFiManager@^2.0.16

build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

